{% set version = "3.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-emstreer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/emstreeR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/emstreeR/emstreeR_{{ version }}.tar.gz
  sha256: ee3dfcf70b71700717481a8d9863f3631aaafe3ce3d4cb12b06e18e291bd05d1

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-mlpack
    - r-scatterplot3d
    - r-sf
  run:
    - r-base
    - r-ggplot2
    - r-mlpack
    - r-scatterplot3d
    - r-sf

test:
  commands:
    - $R -e "library('emstreeR')"           # [not win]
    - "\"%R%\" -e \"library('emstreeR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=emstreeR
  dev_url: https://github.com/allanvc/emstreeR
  license: BSD-3-Clause
  summary: Fast and easily computes an Euclidean Minimum Spanning Tree (EMST) from data, relying on the R API for 'mlpack' - the C++ Machine Learning Library (Curtin et. al., 2013). 'emstreeR' uses the Dual-Tree Boruvka (March, Ram, Gray, 2010, <doi:10.1145/1835804.1835882>), which is theoretically and empirically the fastest
    algorithm for computing an EMST. This package also provides functions and an S3 method for readily plotting Minimum Spanning Trees (MST) using either the style of the 'base', 'scatterplot3d', or 'ggplot2' libraries.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59
